#!/usr/bin/env python3
"""Requirement traceability checker and renderer.

Source of truth: docs/traceability.csv (one row per requirement in
docs/requirements.csv, which was extracted verbatim from the master build
package). This script:

  * verifies every Version 1 requirement, mandatory scenario and release gate
    is mapped (RG-01);
  * verifies statuses use only the allowed vocabulary (Appendix A);
  * for every row marked Passed, verifies each referenced test file exists and
    that at least one test source mentions the requirement ID, so "Passed" is
    backed by executable verification;
  * renders docs/TRACEABILITY.md.

Usage:
  scripts/traceability.py            # check + render
  scripts/traceability.py --release  # additionally fail unless every row is Passed
                                     # or Deferred by Version 1 Scope
"""
from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from collections import Counter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ALLOWED = {
    "Not Started", "In Progress", "Blocked", "Manual Review Required", "Failed", "Passed",
    "Deferred by Version 1 Scope",
}
TEST_DIRS = ["backend/src/test", "android/app/src/test", "android/app/src/androidTest", "android/core/src/test", "scripts/tests"]
FIELDS = ["id", "work_package", "design_ref", "code_ref", "test_ref", "status", "evidence"]


def read_csv(path: str) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def test_corpus() -> str:
    chunks = []
    for d in TEST_DIRS:
        base = os.path.join(ROOT, d)
        for dirpath, _, files in os.walk(base):
            for name in files:
                if name.endswith((".kt", ".py", ".kts", ".sh")):
                    with open(os.path.join(dirpath, name), encoding="utf-8", errors="replace") as f:
                        chunks.append(f.read())
    return "\n".join(chunks)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--release", action="store_true")
    ap.add_argument("--no-render", action="store_true")
    args = ap.parse_args()

    reqs = read_csv(os.path.join(ROOT, "docs/requirements.csv"))
    trace = read_csv(os.path.join(ROOT, "docs/traceability.csv"))
    by_id = {r["id"]: r for r in trace}
    errors: list[str] = []

    for r in reqs:
        if r["id"] not in by_id:
            errors.append(f"{r['id']}: not mapped in docs/traceability.csv")
    for r in trace:
        if r["id"] not in {x["id"] for x in reqs}:
            errors.append(f"{r['id']}: traceability row has no matching requirement")
        if r["status"] not in ALLOWED:
            errors.append(f"{r['id']}: invalid status '{r['status']}'")

    corpus = test_corpus()
    for r in trace:
        if r["status"] != "Passed":
            continue
        if not r["test_ref"].strip():
            errors.append(f"{r['id']}: Passed without a test reference")
        for ref in filter(None, (x.strip() for x in r["test_ref"].split(";"))):
            path = ref.split("#")[0].strip()
            if path and not os.path.exists(os.path.join(ROOT, path)):
                errors.append(f"{r['id']}: referenced test file does not exist: {path}")
        if not re.search(r"(?<![A-Z0-9-])" + re.escape(r["id"]) + r"(?![0-9])", corpus):
            errors.append(f"{r['id']}: Passed but no test mentions the requirement ID")
        if not r["evidence"].strip():
            errors.append(f"{r['id']}: Passed without evidence")

    counts = Counter(r["status"] for r in trace)
    if args.release:
        for r in trace:
            if r["status"] not in ("Passed", "Deferred by Version 1 Scope"):
                errors.append(f"{r['id']}: release requires Passed but status is {r['status']}")

    if not args.no_render:
        render(reqs, by_id, counts)

    total = len(reqs)
    mapped = sum(1 for r in reqs if r["id"] in by_id)
    print(f"Requirements mapped: {mapped}/{total} ({100 * mapped // max(total, 1)}%)")
    for status in sorted(counts):
        print(f"  {status}: {counts[status]}")
    if errors:
        print("\nTraceability errors:")
        for e in errors:
            print("  - " + e)
        return 1
    print("Traceability check passed.")
    return 0


def render(reqs: list[dict], by_id: dict, counts: Counter) -> None:
    out = [
        "# Requirement Traceability Matrix",
        "",
        "Generated by `scripts/traceability.py` from `docs/traceability.csv`. Do not edit by hand.",
        "Requirement text is quoted from the master build package (`docs/requirements.csv`).",
        "",
        "Allowed statuses: Not Started, In Progress, Blocked, Manual Review Required, Failed, Passed, Deferred by Version 1 Scope.",
        "",
        "## Summary",
        "",
        "| Status | Count |",
        "|---|---|",
    ]
    for s in sorted(counts):
        out.append(f"| {s} | {counts[s]} |")
    out += ["", "## Matrix", "", "| Requirement | WP | Design reference | Code reference | Test reference | Status | Evidence |", "|---|---|---|---|---|---|---|"]
    for r in reqs:
        t = by_id.get(r["id"], {})
        text = r["requirement"].replace("|", "\\|")
        cell = lambda k: (t.get(k) or "").replace("|", "\\|").replace(";", "<br>")  # noqa: E731
        out.append(f"| **{r['id']}** {text} | {cell('work_package')} | {cell('design_ref')} | {cell('code_ref')} | {cell('test_ref')} | {t.get('status', 'Not Started')} | {cell('evidence')} |")
    with open(os.path.join(ROOT, "docs/TRACEABILITY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    sys.exit(main())
